---
  # IP address this App will run on, default is localhost
  address: localhost
  # specify port, default is 8050
  port: 8050
  # color codes for entity types following the orders below
  default_color_codes:
    - "#1f77b4"
    - "#ff7f0e"
    - "#2ca02c"
    - "#d62728"
    - "#9467bd"
    - "#8c564b"
    - "#e377c2"
    - "#7f7f7f"
    - "#bcbd22"
    - "#17becf"
    - "#FFD700"
    - "#FFA07A"
    - "#00FFFF"
    - "#FF69B4"
    - "#00FF00"
    - "#FFFF00"
    - "#FF4500"
    - "#7FFFD4"
    - "#BA55D3"
    - "#ADFF2F"
    - "#8A2BE2"
    - "#32CD32"
    - "#FF6347"
    - "#87CEEB"
    - "#FF8C00"
    - "#40E0D0"
    - "#9370DB"
    - "#FFDAB9"
    - "#20B2AA"
    - "#FFC0CB"
    - "#00CED1"
    - "#DDA0DD"
    - "#48D1CC"
    - "#FF1493"
    - "#66CDAA"
    - "#00BFFF"
    - "#FFDEAD"
    - "#00FA9A"
    - "#F0E68C"
    - "#1E90FF"
    - "#FFE4E1"
    - "#FFA500"
    - "#87CEFA"
    - "#FF00FF"
    - "#00FF7F"
    - "#FF4500"
    - "#8FBC8F"
    - "#FF69B4"
    - "#B0E0E6"
    - "#FA8072"
    - "#98FB98"
    - "#DB7093"
    - "#F08080"
    - "#4682B4"
    - "#D2B48C"
    - "#8B008B"
    - "#00CED1"
    - "#556B2F"
    - "#8B4513"
    - "#4682B4"
